repos:
  - repo: https://github.com/psf/black
    rev: 26.5.1
    hooks:
      - id: black

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-ast
      - id: check-case-conflict
      - id: check-json
      - id: check-yaml
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: [--fix=lf]
        exclude: ^(\.github/ISSUE_TEMPLATE/.*|requirements\.txt)$
      - id: trailing-whitespace

  - repo: https://github.com/pycqa/flake8
    rev: 7.3.0
    hooks:
      - id: flake8
        args: [--jobs=1]

  - repo: local
    hooks:
      - id: needs-hash
        name: commit message needs an issue reference
        language: pygrep
        entry: '#\d+'
        args: [--multiline, --negate]
        stages: [commit-msg]

      - id: pytest-check
        name: pytest
        entry: python -m pytest test_helper.py test_main.py
        language: system
        pass_filenames: false
        always_run: true
        stages: [pre-commit]
